apiVersion: v1 
kind: Service
metadata:
  name: testservice-depl-node-port
spec:
  type: NodePort
  selector:
    component: web-depl
  ports:
     - port: 8099
       targetPort: 8099
       nodePort: 30008