apiVersion: v1 
kind: Service
metadata:
  name: react-app-node-port
spec:
  type: NodePort
  selector:
    component: react-app-pod
  ports:
     - port: 3000
       targetPort: 3000
       nodePort: 30028