apiVersion: v1
kind: Pod
metadata:   
  name: react-app-pod
  labels:
    component: react-app-pod
spec:
  containers:
    - name: client
      image: stephengrider/multi-client
      ports:
        - containerPort: 3000