apiVersion: v1 
kind: Service
metadata:
  name: testservice-node-port
spec:
  type: NodePort
  selector:
    component: testservice-pod
  ports:
     - port: 8099
       targetPort: 8099
       nodePort: 30008